repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: python
        entry: black --check
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]
      - id: isort
        name: isort (python)
        language: python
        entry: isort --check-only
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]
      - id: bandit
        name: bandit
        language: python
        entry: bandit
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python]
